[[block]]
block = "custom"
command = "nix shell nixpkgs#python313 --command python3 /nix/store/91dlf5fq3a5b99vdk46qhcf9871lmp82-get-fcitx-im-label.py"
interval = "once"
signal = 4

[[block]]
block = "custom"
command = "sleep 1 && niri msg -j focused-window | jq 'if .==null then halt elif .app_id==\"Alacritty\" and (.title | test(\"^\\\\d+ --client-id \\\\d+ - \\\\(term://.+//\\\\d+:yazi .+ --chooser-file .+\\\\) - NVIM$\")) then \"Yazi on NVIM\" elif .app_id==\"firefox\" then \"Firefox\" else .title end' -r"
hide_when_empty = true
interval = 3

[[block]]
block = "custom"
interval = 1
#command = "localectl|awk 'NR==4 {print $3}'"
command = ''' /home/dromi/repo/env/scripts/layout/i3status-rust-wrapper.sh  '''

[[block]]
block = "custom"
interval = 1
#command = "localectl|awk 'NR==4 {print $3}'"
command = ''' cat /home/dromi/.cache/tmp/layout_index  '''


[[block]]
alert = 10.0
block = "disk_space"
info_type = "available"
interval = 60
path = "/"
warning = 20.0

[[block]]
block = "memory"
format = " $icon $mem_used_percents "
format_alt = " $icon swap $swap_used_percents "

[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization "
#format_alt = " $icon $frequency{ $boost|} "

[[block]]
block = "load"
format = " $icon $1m "
interval = 1



[[block]]
block = "sound"

#[[block]]
#block = "custom"
#command = ''' cat /sys/class/thermal/thermal_zone0/temp | awk '{printf("%.1f\n",$1/1000)}' '''
#command = "bash -c kitty 'curl de.wttr.in/Diepoldsau?0'"
#command = "kitty --title Terminal1 bash -c \"curl de.wttr.in/Diepoldsau?0; exec bash\""




# Enable it, if you device have a battery
# later it should detect automatically, if it owns one.
#[[block]]
#block = "battery"
#format = " $percentage {$time_remaining.dur(hms:true, min_unit:m) |}"


[[block]]
block = "time"
format = " $timestamp.datetime(f:'%a %d/%m %R') "
#interval = 60
interval = 1

[icons]
#icons = "material-nf"
icons = "awesome4"
[icons.overrides]

[theme]
#theme = "solarized-dark"
theme = "space-villain"

