#!/bin/bash


c="env/dotfiles"
src="$HOME/repo/env/"
configs="dotfiles/config"
p="$src/$configs"

ln -sf $src/dotfiles/home/.bashrc     ~/
ln -sf $src/dotfiles/home/.tmux.conf  ~/
ln -sf $src/dotfiles/home/.vimrc      ~/

a="$HOME/.config/i3bar-river/"
b="$HOME/.config/i3status-rust/"
c="$HOME/.config/river/"
d="$HOME/.config/kitty/"
e="$HOME/.config/vifm/"

# Is this valid? - to check if all configs aren't missing.
#files=($a $b $c $d $e)

mkdir -p {$a,$b,$c,$d,$e}

# No I know that the first argument of ln is relative to the second argument.
# But bruh, this information was not relevant for this...
ln -sf $p/i3bar-river/*     $a
ln -sf $p/i3status-rust/*   $b
ln -sf $p/river/*           $c

ln -sf $p/kitty/*           $d
ln -sf $p/vifm/*            $e


# Manual clear
function clear () {

	rm -fr $a $b $c $d $e
 	rm -f $HOME/{.bashrc,.tmux.conf,.vimrc}
   	echo "INFO: All files are cleared(deleted)."
}

# to make possible to invoke function clear with 'cpf clear'
if [ ! -z "$1" ]; then
    "$1"
fi

